language: python
env:
    - MPLBACKEND='agg'
    -
python:
    - '2.7'
    - '3.5'
    - '3.6'
install:
    - pip install . # install package
    - pip install -r requirements.txt # install requires
    - if [[ -n $MPLBACKEND ]]; then pip install matplotlib; fi
    - pip install shapely coveralls # only for testing
script:
    - nosetests --verbose --with-coverage --cover-package=cartoframes
after_success:
    - coveralls
