language: python
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
install:
    - pip install .
    - pip install -r requirements.txt
    - pip install coverage
script:
    - nosetests --verbose --with-coverage --cover-package=cartoframes
after_success:
      coveralls
