language: python
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
install:
    - pip install .
    - pip install -r requirements.txt
    - pip install nose coverage
    - pip install coveralls
script:
    - make test
    - python setup.py nosetests --with-coverage --cover-package pypiview
after_sucess:
      coveralls
